import networkx as nx
import matplotlib.pyplot as plt
goarn_network= nx.Graph()

goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO HQ",weight=1)
goarn_network.add_edge("WHO HQ", "WHO Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "WHO HQ",weight=1)
goarn_network.add_edge("National Task Force Uganda", "WHO HQ",weight=1)
goarn_network.add_edge("MSF International", "WHO HQ",weight=1)
goarn_network.add_edge("Epicentre France", "WHO HQ",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO HQ",weight=1)
goarn_network.add_edge("CDC Atlanta", "WHO HQ",weight=2)
goarn_network.add_edge("ISS Italy", "WHO HQ",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "WHO HQ",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO HQ",weight=1)
goarn_network.add_edge("WHO HQ", "WHO_AFRO",weight=2)
goarn_network.add_edge("Action Contre la Faim", "WHO HQ",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "WHO HQ",weight=1)
goarn_network.add_edge("ACORD-UK", "WHO HQ",weight=1)
goarn_network.add_edge("Catholic Relief Services", "WHO HQ",weight=1)
goarn_network.add_edge("Lacor Hospital", "WHO HQ",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO HQ",weight=1)
goarn_network.add_edge("ICRC", "WHO HQ",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "WHO HQ",weight=1)
goarn_network.add_edge("WHO HQ", "World Food Programme",weight=1)
goarn_network.add_edge("WHO HQ", "World Vision",weight=1)
goarn_network.add_edge("UNICEF", "WHO HQ",weight=2)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO HQ",weight=1)
goarn_network.add_edge("USAID", "WHO HQ",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "National Task Force Uganda",weight=1)
goarn_network.add_edge("MSF International", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("Epicentre France", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC Atlanta", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("ISS Italy", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("ACORD-UK", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("Catholic Relief Services", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("Lacor Hospital", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "Red Crescent societies",weight=1)
goarn_network.add_edge("ICRC", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "World Food Programme",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "World Vision",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "UNICEF",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "USAID",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "WHO Uganda",weight=2)
goarn_network.add_edge("National Task Force Uganda", "WHO Uganda",weight=1)
goarn_network.add_edge("MSF International", "WHO Uganda",weight=1)
goarn_network.add_edge("Epicentre France", "WHO Uganda",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO Uganda",weight=1)
goarn_network.add_edge("CDC Atlanta", "WHO Uganda",weight=1)
goarn_network.add_edge("ISS Italy", "WHO Uganda",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "WHO Uganda",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO Uganda",weight=1)
goarn_network.add_edge("WHO Uganda", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "WHO Uganda",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "WHO Uganda",weight=1)
goarn_network.add_edge("ACORD-UK", "WHO Uganda",weight=1)
goarn_network.add_edge("Catholic Relief Services", "WHO Uganda",weight=1)
goarn_network.add_edge("Lacor Hospital", "WHO Uganda",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO Uganda",weight=1)
goarn_network.add_edge("ICRC", "WHO Uganda",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "WHO Uganda",weight=1)
goarn_network.add_edge("WHO Uganda", "World Food Programme",weight=1)
goarn_network.add_edge("WHO Uganda", "World Vision",weight=1)
goarn_network.add_edge("UNICEF", "WHO Uganda",weight=2)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO Uganda",weight=1)
goarn_network.add_edge("USAID", "WHO Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "National Task Force Uganda",weight=1)
goarn_network.add_edge("MSF International", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("Epicentre France", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC Atlanta", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("ISS Italy", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("ACORD-UK", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("Catholic Relief Services", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("Lacor Hospital", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "Red Crescent societies",weight=1)
goarn_network.add_edge("ICRC", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "World Food Programme",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "World Vision",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "UNICEF",weight=2)
goarn_network.add_edge("Ministry of Health of Uganda", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "USAID",weight=1)
goarn_network.add_edge("MSF International", "National Task Force Uganda",weight=1)
goarn_network.add_edge("Epicentre France", "National Task Force Uganda",weight=1)
goarn_network.add_edge("National Task Force Uganda", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC Atlanta", "National Task Force Uganda",weight=1)
goarn_network.add_edge("ISS Italy", "National Task Force Uganda",weight=1)
goarn_network.add_edge("National Task Force Uganda", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "National Task Force Uganda",weight=1)
goarn_network.add_edge("National Task Force Uganda", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "National Task Force Uganda",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "National Task Force Uganda",weight=1)
goarn_network.add_edge("ACORD-UK", "National Task Force Uganda",weight=1)
goarn_network.add_edge("Catholic Relief Services", "National Task Force Uganda",weight=1)
goarn_network.add_edge("Lacor Hospital", "National Task Force Uganda",weight=1)
goarn_network.add_edge("National Task Force Uganda", "Red Crescent societies",weight=1)
goarn_network.add_edge("ICRC", "National Task Force Uganda",weight=1)
goarn_network.add_edge("National Task Force Uganda", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("National Task Force Uganda", "World Food Programme",weight=1)
goarn_network.add_edge("National Task Force Uganda", "World Vision",weight=1)
goarn_network.add_edge("National Task Force Uganda", "UNICEF",weight=1)
goarn_network.add_edge("National Task Force Uganda", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("National Task Force Uganda", "USAID",weight=1)
goarn_network.add_edge("Epicentre France", "MSF International",weight=1)
goarn_network.add_edge("MSF International", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC Atlanta", "MSF International",weight=1)
goarn_network.add_edge("ISS Italy", "MSF International",weight=1)
goarn_network.add_edge("MSF International", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("MSF International", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("MSF International", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "MSF International",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "MSF International",weight=1)
goarn_network.add_edge("ACORD-UK", "MSF International",weight=1)
goarn_network.add_edge("Catholic Relief Services", "MSF International",weight=1)
goarn_network.add_edge("Lacor Hospital", "MSF International",weight=1)
goarn_network.add_edge("MSF International", "Red Crescent societies",weight=1)
goarn_network.add_edge("ICRC", "MSF International",weight=1)
goarn_network.add_edge("MSF International", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("MSF International", "World Food Programme",weight=1)
goarn_network.add_edge("MSF International", "World Vision",weight=1)
goarn_network.add_edge("MSF International", "UNICEF",weight=1)
goarn_network.add_edge("MSF International", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("MSF International", "USAID",weight=1)
goarn_network.add_edge("Epicentre France", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC Atlanta", "Epicentre France",weight=2)
goarn_network.add_edge("Epicentre France", "ISS Italy",weight=1)
goarn_network.add_edge("Epicentre France", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Epicentre France", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("Epicentre France", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "Epicentre France",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "Epicentre France",weight=1)
goarn_network.add_edge("ACORD-UK", "Epicentre France",weight=1)
goarn_network.add_edge("Catholic Relief Services", "Epicentre France",weight=1)
goarn_network.add_edge("Epicentre France", "Lacor Hospital",weight=1)
goarn_network.add_edge("Epicentre France", "Red Crescent societies",weight=1)
goarn_network.add_edge("Epicentre France", "ICRC",weight=1)
goarn_network.add_edge("Epicentre France", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("Epicentre France", "World Food Programme",weight=1)
goarn_network.add_edge("Epicentre France", "World Vision",weight=1)
goarn_network.add_edge("Epicentre France", "UNICEF",weight=1)
goarn_network.add_edge("Epicentre France", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Epicentre France", "USAID",weight=1)
goarn_network.add_edge("CDC Atlanta", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("ISS Italy", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("ACORD-UK", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Catholic Relief Services", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Lacor Hospital", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("ICRC", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "World Food Programme",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "World Vision",weight=1)
goarn_network.add_edge("UNICEF", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("USAID", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC Atlanta", "ISS Italy",weight=1)
goarn_network.add_edge("CDC Atlanta", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("CDC Atlanta", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("CDC Atlanta", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "CDC Atlanta",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "CDC Atlanta",weight=1)
goarn_network.add_edge("ACORD-UK", "CDC Atlanta",weight=1)
goarn_network.add_edge("CDC Atlanta", "Catholic Relief Services",weight=1)
goarn_network.add_edge("CDC Atlanta", "Lacor Hospital",weight=1)
goarn_network.add_edge("CDC Atlanta", "Red Crescent societies",weight=1)
goarn_network.add_edge("CDC Atlanta", "ICRC",weight=1)
goarn_network.add_edge("CDC Atlanta", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("CDC Atlanta", "World Food Programme",weight=1)
goarn_network.add_edge("CDC Atlanta", "World Vision",weight=1)
goarn_network.add_edge("CDC Atlanta", "UNICEF",weight=2)
goarn_network.add_edge("CDC Atlanta", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("CDC Atlanta", "USAID",weight=1)
goarn_network.add_edge("ISS Italy", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("ISS Italy", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("ISS Italy", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "ISS Italy",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "ISS Italy",weight=1)
goarn_network.add_edge("ACORD-UK", "ISS Italy",weight=1)
goarn_network.add_edge("Catholic Relief Services", "ISS Italy",weight=1)
goarn_network.add_edge("ISS Italy", "Lacor Hospital",weight=1)
goarn_network.add_edge("ISS Italy", "Red Crescent societies",weight=1)
goarn_network.add_edge("ICRC", "ISS Italy",weight=1)
goarn_network.add_edge("ISS Italy", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("ISS Italy", "World Food Programme",weight=1)
goarn_network.add_edge("ISS Italy", "World Vision",weight=1)
goarn_network.add_edge("ISS Italy", "UNICEF",weight=1)
goarn_network.add_edge("ISS Italy", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("ISS Italy", "USAID",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("ACORD-UK", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Catholic Relief Services", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Lacor Hospital", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Red Crescent societies", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("ICRC", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "Sendai Quarantine Station",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "World Food Programme",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "World Vision",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "UNICEF",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Sendai Quarantine Station", "USAID",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("ACORD-UK", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("Catholic Relief Services", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("Lacor Hospital", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "Red Crescent societies",weight=1)
goarn_network.add_edge("ICRC", "National Institute for Infectious Diseases Japan",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "World Food Programme",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "World Vision",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "UNICEF",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "USAID",weight=1)
goarn_network.add_edge("Action Contre la Faim", "WHO_AFRO",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "WHO_AFRO",weight=1)
goarn_network.add_edge("ACORD-UK", "WHO_AFRO",weight=1)
goarn_network.add_edge("Catholic Relief Services", "WHO_AFRO",weight=1)
goarn_network.add_edge("Lacor Hospital", "WHO_AFRO",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO_AFRO",weight=4)
goarn_network.add_edge("ICRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "WHO_AFRO",weight=1)
goarn_network.add_edge("WHO_AFRO", "World Food Programme",weight=1)
goarn_network.add_edge("WHO_AFRO", "World Vision",weight=1)
goarn_network.add_edge("UNICEF", "WHO_AFRO",weight=1)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO_AFRO",weight=1)
goarn_network.add_edge("USAID", "WHO_AFRO",weight=1)
goarn_network.add_edge("Action Contre la Faim", "African Medical and Research Foundation",weight=1)
goarn_network.add_edge("ACORD-UK", "Action Contre la Faim",weight=1)
goarn_network.add_edge("Action Contre la Faim", "Catholic Relief Services",weight=1)
goarn_network.add_edge("Action Contre la Faim", "Lacor Hospital",weight=1)
goarn_network.add_edge("Action Contre la Faim", "Red Crescent societies",weight=1)
goarn_network.add_edge("Action Contre la Faim", "ICRC",weight=1)
goarn_network.add_edge("Action Contre la Faim", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("Action Contre la Faim", "World Food Programme",weight=1)
goarn_network.add_edge("Action Contre la Faim", "World Vision",weight=1)
goarn_network.add_edge("Action Contre la Faim", "UNICEF",weight=1)
goarn_network.add_edge("Action Contre la Faim", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Action Contre la Faim", "USAID",weight=1)
goarn_network.add_edge("ACORD-UK", "African Medical and Research Foundation",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "Catholic Relief Services",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "Lacor Hospital",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "Red Crescent societies",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "ICRC",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "World Food Programme",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "World Vision",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "UNICEF",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("African Medical and Research Foundation", "USAID",weight=1)
goarn_network.add_edge("ACORD-UK", "Catholic Relief Services",weight=1)
goarn_network.add_edge("ACORD-UK", "Lacor Hospital",weight=1)
goarn_network.add_edge("ACORD-UK", "Red Crescent societies",weight=1)
goarn_network.add_edge("ACORD-UK", "ICRC",weight=1)
goarn_network.add_edge("ACORD-UK", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("ACORD-UK", "World Food Programme",weight=1)
goarn_network.add_edge("ACORD-UK", "World Vision",weight=1)
goarn_network.add_edge("ACORD-UK", "UNICEF",weight=1)
goarn_network.add_edge("ACORD-UK", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("ACORD-UK", "USAID",weight=1)
goarn_network.add_edge("Catholic Relief Services", "Lacor Hospital",weight=1)
goarn_network.add_edge("Catholic Relief Services", "Red Crescent societies",weight=1)
goarn_network.add_edge("Catholic Relief Services", "ICRC",weight=1)
goarn_network.add_edge("Catholic Relief Services", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("Catholic Relief Services", "World Food Programme",weight=1)
goarn_network.add_edge("Catholic Relief Services", "World Vision",weight=1)
goarn_network.add_edge("Catholic Relief Services", "UNICEF",weight=1)
goarn_network.add_edge("Catholic Relief Services", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Catholic Relief Services", "USAID",weight=1)
goarn_network.add_edge("Lacor Hospital", "Red Crescent societies",weight=1)
goarn_network.add_edge("ICRC", "Lacor Hospital",weight=1)
goarn_network.add_edge("Lacor Hospital", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("Lacor Hospital", "World Food Programme",weight=1)
goarn_network.add_edge("Lacor Hospital", "World Vision",weight=1)
goarn_network.add_edge("Lacor Hospital", "UNICEF",weight=1)
goarn_network.add_edge("Lacor Hospital", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Lacor Hospital", "USAID",weight=1)
goarn_network.add_edge("ICRC", "Red Crescent societies",weight=1)
goarn_network.add_edge("Red Crescent societies", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("Red Crescent societies", "World Food Programme",weight=1)
goarn_network.add_edge("Red Crescent societies", "World Vision",weight=1)
goarn_network.add_edge("Red Crescent societies", "UNICEF",weight=1)
goarn_network.add_edge("Red Crescent societies", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Red Crescent societies", "USAID",weight=1)
goarn_network.add_edge("ICRC", "Save the Children-Denmark",weight=1)
goarn_network.add_edge("ICRC", "World Food Programme",weight=1)
goarn_network.add_edge("ICRC", "World Vision",weight=1)
goarn_network.add_edge("ICRC", "UNICEF",weight=1)
goarn_network.add_edge("ICRC", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("ICRC", "USAID",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "World Food Programme",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "World Vision",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "UNICEF",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Save the Children-Denmark", "USAID",weight=1)
goarn_network.add_edge("World Food Programme", "World Vision",weight=1)
goarn_network.add_edge("UNICEF", "World Food Programme",weight=2)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "World Food Programme",weight=1)
goarn_network.add_edge("USAID", "World Food Programme",weight=1)
goarn_network.add_edge("UNICEF", "World Vision",weight=1)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "World Vision",weight=1)
goarn_network.add_edge("USAID", "World Vision",weight=1)
goarn_network.add_edge("UNICEF", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("UNICEF", "USAID",weight=1)
goarn_network.add_edge("USAID", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("CIRMF", "WHO Gabon",weight=2)
goarn_network.add_edge("Ministry of Health Gabon", "WHO Gabon",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO Gabon",weight=2)
goarn_network.add_edge("Epicentre France", "WHO Gabon",weight=1)
goarn_network.add_edge("Comite Politique Interministeriel", "WHO Gabon",weight=1)
goarn_network.add_edge("Comite de Coordination Generale Gabon", "WHO Gabon",weight=1)
goarn_network.add_edge("Comite Provincial Gabon", "WHO Gabon",weight=1)
goarn_network.add_edge("Comite de Coordination Technique et Scientifique de Lutte Gabon", "WHO Gabon",weight=1)
goarn_network.add_edge("CDC Atlanta", "WHO Gabon",weight=1)
goarn_network.add_edge("CIRMF", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("CIRMF", "MSF Belgium",weight=4)
goarn_network.add_edge("CIRMF", "Epicentre France",weight=1)
goarn_network.add_edge("CIRMF", "Comite Politique Interministeriel",weight=1)
goarn_network.add_edge("CIRMF", "Comite de Coordination Generale Gabon",weight=1)
goarn_network.add_edge("CIRMF", "Comite Provincial Gabon",weight=1)
goarn_network.add_edge("CIRMF", "Comite de Coordination Technique et Scientifique de Lutte Gabon",weight=1)
goarn_network.add_edge("CDC Atlanta", "CIRMF",weight=2)
goarn_network.add_edge("MSF Belgium", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("Epicentre France", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("Comite Politique Interministeriel", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("Comite de Coordination Generale Gabon", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("Comite Provincial Gabon", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("Comite de Coordination Technique et Scientifique de Lutte Gabon", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("CDC Atlanta", "Ministry of Health Gabon",weight=1)
goarn_network.add_edge("Epicentre France", "MSF Belgium",weight=1)
goarn_network.add_edge("Comite Politique Interministeriel", "MSF Belgium",weight=1)
goarn_network.add_edge("Comite de Coordination Generale Gabon", "MSF Belgium",weight=1)
goarn_network.add_edge("Comite Provincial Gabon", "MSF Belgium",weight=1)
goarn_network.add_edge("Comite de Coordination Technique et Scientifique de Lutte Gabon", "MSF Belgium",weight=1)
goarn_network.add_edge("CDC Atlanta", "MSF Belgium",weight=2)
goarn_network.add_edge("Comite Politique Interministeriel", "Epicentre France",weight=1)
goarn_network.add_edge("Comite de Coordination Generale Gabon", "Epicentre France",weight=1)
goarn_network.add_edge("Comite Provincial Gabon", "Epicentre France",weight=1)
goarn_network.add_edge("Comite de Coordination Technique et Scientifique de Lutte Gabon", "Epicentre France",weight=1)
goarn_network.add_edge("Comite Politique Interministeriel", "Comite de Coordination Generale Gabon",weight=1)
goarn_network.add_edge("Comite Politique Interministeriel", "Comite Provincial Gabon",weight=1)
goarn_network.add_edge("Comite Politique Interministeriel", "Comite de Coordination Technique et Scientifique de Lutte Gabon",weight=1)
goarn_network.add_edge("CDC Atlanta", "Comite Politique Interministeriel",weight=1)
goarn_network.add_edge("Comite Provincial Gabon", "Comite de Coordination Generale Gabon",weight=1)
goarn_network.add_edge("Comite de Coordination Generale Gabon", "Comite de Coordination Technique et Scientifique de Lutte Gabon",weight=1)
goarn_network.add_edge("CDC Atlanta", "Comite de Coordination Generale Gabon",weight=1)
goarn_network.add_edge("Comite Provincial Gabon", "Comite de Coordination Technique et Scientifique de Lutte Gabon",weight=1)
goarn_network.add_edge("CDC Atlanta", "Comite Provincial Gabon",weight=1)
goarn_network.add_edge("CDC Atlanta", "Comite de Coordination Technique et Scientifique de Lutte Gabon",weight=1)
goarn_network.add_edge("Ministry of Health Algeria", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Ministry of Health Algeria",weight=1)
goarn_network.add_edge("Kazakh Scientific Centre for Quarantine and Zoonotic Disease", "Ministry of Health Algeria",weight=1)
goarn_network.add_edge("Institut Pasteur France", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Kazakh Scientific Centre for Quarantine and Zoonotic Disease", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Kazakh Scientific Centre for Quarantine and Zoonotic Disease",weight=1)
goarn_network.add_edge("IRD", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("CIRMF", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO_AFRO",weight=2)
goarn_network.add_edge("Ministry of Health DRC", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("MSF Holland", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "National Control Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("ECHO", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("French Cooperation", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "Red Crescent societies",weight=3)
goarn_network.add_edge("Ministry of Health DRC", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("CIRMF", "IRD",weight=1)
goarn_network.add_edge("IRD", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("IRD", "WHO_AFRO",weight=1)
goarn_network.add_edge("IRD", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("IRD", "MSF Holland",weight=1)
goarn_network.add_edge("IRD", "National Control Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "IRD",weight=1)
goarn_network.add_edge("ECHO", "IRD",weight=1)
goarn_network.add_edge("French Cooperation", "IRD",weight=1)
goarn_network.add_edge("IRD", "Red Crescent societies",weight=3)
goarn_network.add_edge("IRD", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("CIRMF", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("CIRMF", "WHO_AFRO",weight=1)
goarn_network.add_edge("CIRMF", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("CIRMF", "MSF Holland",weight=1)
goarn_network.add_edge("CIRMF", "National Control Committee DRC",weight=1)
goarn_network.add_edge("CIRMF", "Congolese Ministries of Defence and Foresty",weight=1)
goarn_network.add_edge("CIRMF", "ECHO",weight=1)
goarn_network.add_edge("CIRMF", "French Cooperation",weight=1)
goarn_network.add_edge("CIRMF", "Red Crescent societies",weight=3)
goarn_network.add_edge("CIRMF", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("National Coordination Committee DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("National Coordination Committee DRC", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("MSF Holland", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("National Control Committee DRC", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("ECHO", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("French Cooperation", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("National Coordination Committee DRC", "Red Crescent societies",weight=3)
goarn_network.add_edge("National Coordination Committee DRC", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("WHO Congo Brazzaville", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Holland", "WHO_AFRO",weight=1)
goarn_network.add_edge("National Control Committee DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "WHO_AFRO",weight=1)
goarn_network.add_edge("ECHO", "WHO_AFRO",weight=1)
goarn_network.add_edge("French Cooperation", "WHO_AFRO",weight=1)
goarn_network.add_edge("United Nations High Commission for Refugees (UNHCR)", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Holland", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("National Control Committee DRC", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("ECHO", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("French Cooperation", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO Congo Brazzaville",weight=3)
goarn_network.add_edge("United Nations High Commission for Refugees (UNHCR)", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("MSF Holland", "National Control Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "MSF Holland",weight=1)
goarn_network.add_edge("ECHO", "MSF Holland",weight=1)
goarn_network.add_edge("French Cooperation", "MSF Holland",weight=1)
goarn_network.add_edge("MSF Holland", "Red Crescent societies",weight=3)
goarn_network.add_edge("MSF Holland", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "National Control Committee DRC",weight=1)
goarn_network.add_edge("ECHO", "National Control Committee DRC",weight=1)
goarn_network.add_edge("French Cooperation", "National Control Committee DRC",weight=1)
goarn_network.add_edge("National Control Committee DRC", "Red Crescent societies",weight=3)
goarn_network.add_edge("National Control Committee DRC", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "ECHO",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "French Cooperation",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "Red Crescent societies",weight=3)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("ECHO", "French Cooperation",weight=1)
goarn_network.add_edge("ECHO", "Red Crescent societies",weight=3)
goarn_network.add_edge("ECHO", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("French Cooperation", "Red Crescent societies",weight=3)
goarn_network.add_edge("French Cooperation", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("Red Crescent societies", "Red Crescent societies",weight=3)
goarn_network.add_edge("Red Crescent societies", "United Nations High Commission for Refugees (UNHCR)",weight=3)
goarn_network.add_edge("CDC Atlanta", "Kenya Medical Research Institute (KEMRI)",weight=1)
goarn_network.add_edge("Kenya Medical Research Institute (KEMRI)", "WHO South Sudan Early Warning and Response Network (EWARN)",weight=1)
goarn_network.add_edge("Kenya Medical Research Institute (KEMRI)", "WHO HQ",weight=1)
goarn_network.add_edge("Kenya Medical Research Institute (KEMRI)", "UNICEF",weight=1)
goarn_network.add_edge("Kenya Medical Research Institute (KEMRI)", "MSF France",weight=1)
goarn_network.add_edge("Kenya Medical Research Institute (KEMRI)", "WHO DRC",weight=1)
goarn_network.add_edge("CDC Atlanta", "WHO South Sudan Early Warning and Response Network (EWARN)",weight=1)
goarn_network.add_edge("CDC Atlanta", "MSF France",weight=1)
goarn_network.add_edge("CDC Atlanta", "WHO DRC",weight=2)
goarn_network.add_edge("WHO HQ", "WHO South Sudan Early Warning and Response Network (EWARN)",weight=1)
goarn_network.add_edge("UNICEF", "WHO South Sudan Early Warning and Response Network (EWARN)",weight=1)
goarn_network.add_edge("MSF France", "WHO South Sudan Early Warning and Response Network (EWARN)",weight=1)
goarn_network.add_edge("WHO DRC", "WHO South Sudan Early Warning and Response Network (EWARN)",weight=1)
goarn_network.add_edge("MSF France", "WHO HQ",weight=1)
goarn_network.add_edge("WHO DRC", "WHO HQ",weight=2)
goarn_network.add_edge("MSF France", "UNICEF",weight=1)
goarn_network.add_edge("UNICEF", "WHO DRC",weight=2)
goarn_network.add_edge("MSF France", "WHO DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO HQ",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO HQ",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO HQ",weight=1)
goarn_network.add_edge("MSF Switzerland", "WHO HQ",weight=1)
goarn_network.add_edge("Medair", "WHO HQ",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO HQ",weight=1)
goarn_network.add_edge("WHO DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO DRC",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO DRC",weight=3)
goarn_network.add_edge("MSF Switzerland", "WHO DRC",weight=1)
goarn_network.add_edge("Medair", "WHO DRC",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Switzerland", "WHO_AFRO",weight=1)
goarn_network.add_edge("Medair", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("MSF Belgium", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("MSF Switzerland", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Medair", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "MSF Belgium",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "MSF Switzerland",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Medair",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Institut de la Recherche Biomedicale",weight=1)
goarn_network.add_edge("MSF Belgium", "MSF Switzerland",weight=1)
goarn_network.add_edge("MSF Belgium", "Medair",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Switzerland", "Medair",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "MSF Switzerland",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "Medair",weight=1)
goarn_network.add_edge("MSF Belgium", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("MONUC", "MSF Belgium",weight=2)
goarn_network.add_edge("Interchurch Medical Assistance (IMA World Health)", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Belgium", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "MSF Belgium",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "MSF Belgium",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "MSF Belgium",weight=1)
goarn_network.add_edge("ECDC", "MSF Belgium",weight=1)
goarn_network.add_edge("Institut Pasteur France", "MSF Belgium",weight=1)
goarn_network.add_edge("London School of Hygiene and Tropical Medicine", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Belgium", "National University Singapore",weight=1)
goarn_network.add_edge("Public Health Agency of Canada", "WHO DRC",weight=1)
goarn_network.add_edge("MONUC", "WHO DRC",weight=2)
goarn_network.add_edge("Interchurch Medical Assistance (IMA World Health)", "WHO DRC",weight=1)
goarn_network.add_edge("Swiss Agency for Development and Cooperation", "WHO DRC",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "WHO DRC",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "WHO DRC",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "WHO DRC",weight=1)
goarn_network.add_edge("CIRMF", "WHO DRC",weight=2)
goarn_network.add_edge("ECDC", "WHO DRC",weight=1)
goarn_network.add_edge("Institut Pasteur France", "WHO DRC",weight=1)
goarn_network.add_edge("London School of Hygiene and Tropical Medicine", "WHO DRC",weight=1)
goarn_network.add_edge("National University Singapore", "WHO DRC",weight=1)
goarn_network.add_edge("CDC Atlanta", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("CDC Atlanta", "MONUC",weight=1)
goarn_network.add_edge("CDC Atlanta", "Interchurch Medical Assistance (IMA World Health)",weight=1)
goarn_network.add_edge("CDC Atlanta", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("CDC Atlanta", "Hopital  Cantonal in Geneva",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "CDC Atlanta",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "CDC Atlanta",weight=1)
goarn_network.add_edge("CDC Atlanta", "ECDC",weight=1)
goarn_network.add_edge("CDC Atlanta", "Institut Pasteur France",weight=1)
goarn_network.add_edge("CDC Atlanta", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("CDC Atlanta", "National University Singapore",weight=1)
goarn_network.add_edge("MONUC", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("Interchurch Medical Assistance (IMA World Health)", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("Public Health Agency of Canada", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("CIRMF", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("ECDC", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("London School of Hygiene and Tropical Medicine", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("National University Singapore", "Public Health Agency of Canada",weight=1)
goarn_network.add_edge("Interchurch Medical Assistance (IMA World Health)", "MONUC",weight=1)
goarn_network.add_edge("MONUC", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "MONUC",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "MONUC",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "MONUC",weight=1)
goarn_network.add_edge("CIRMF", "MONUC",weight=2)
goarn_network.add_edge("ECDC", "MONUC",weight=1)
goarn_network.add_edge("Institut Pasteur France", "MONUC",weight=1)
goarn_network.add_edge("London School of Hygiene and Tropical Medicine", "MONUC",weight=1)
goarn_network.add_edge("MONUC", "National University Singapore",weight=1)
goarn_network.add_edge("Interchurch Medical Assistance (IMA World Health)", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "Interchurch Medical Assistance (IMA World Health)",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "Interchurch Medical Assistance (IMA World Health)",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "Interchurch Medical Assistance (IMA World Health)",weight=1)
goarn_network.add_edge("CIRMF", "Interchurch Medical Assistance (IMA World Health)",weight=1)
goarn_network.add_edge("ECDC", "Interchurch Medical Assistance (IMA World Health)",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Interchurch Medical Assistance (IMA World Health)",weight=1)
goarn_network.add_edge("Interchurch Medical Assistance (IMA World Health)", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("Interchurch Medical Assistance (IMA World Health)", "National University Singapore",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("CIRMF", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("ECDC", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("London School of Hygiene and Tropical Medicine", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("National University Singapore", "Swiss Agency for Development and Cooperation",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "Hopital  Cantonal in Geneva",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "Hopital  Cantonal in Geneva",weight=1)
goarn_network.add_edge("CIRMF", "Hopital  Cantonal in Geneva",weight=1)
goarn_network.add_edge("ECDC", "Hopital  Cantonal in Geneva",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "Institut Pasteur France",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("Hopital  Cantonal in Geneva", "National University Singapore",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "Bernard-Nocht Institute for Tropical Medicine",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "CIRMF",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "ECDC",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "Institut Pasteur France",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("African Field Epidemiology Network", "National University Singapore",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "CIRMF",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "ECDC",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "Institut Pasteur France",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("Bernard-Nocht Institute for Tropical Medicine", "National University Singapore",weight=1)
goarn_network.add_edge("CIRMF", "ECDC",weight=1)
goarn_network.add_edge("CIRMF", "Institut Pasteur France",weight=1)
goarn_network.add_edge("CIRMF", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("CIRMF", "National University Singapore",weight=1)
goarn_network.add_edge("ECDC", "Institut Pasteur France",weight=1)
goarn_network.add_edge("ECDC", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("ECDC", "National University Singapore",weight=1)
goarn_network.add_edge("Institut Pasteur France", "London School of Hygiene and Tropical Medicine",weight=1)
goarn_network.add_edge("Institut Pasteur France", "National University Singapore",weight=1)
goarn_network.add_edge("London School of Hygiene and Tropical Medicine", "National University Singapore",weight=1)
goarn_network.add_edge("MSF", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("MSF", "WHO Uganda",weight=1)
goarn_network.add_edge("MSF", "UNICEF",weight=1)
goarn_network.add_edge("CIRMF", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("CIRMF", "NICD South Africa",weight=1)
goarn_network.add_edge("CIRMF", "Caritas (Belgium)",weight=1)
goarn_network.add_edge("CIRMF", "Congolese Red Cross (DRC)",weight=1)
goarn_network.add_edge("CIRMF", "UNICEF",weight=1)
goarn_network.add_edge("CIRMF", "World Food Programme",weight=1)
goarn_network.add_edge("National de Recherches Biologiques (INRB)", "WHO DRC",weight=1)
goarn_network.add_edge("NICD South Africa", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("MSF Belgium", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("National de Recherches Biologiques (INRB)", "UNICEF",weight=1)
goarn_network.add_edge("MONUC", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("National de Recherches Biologiques (INRB)", "World Food Programme",weight=1)
goarn_network.add_edge("NICD South Africa", "WHO DRC",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "WHO DRC",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "WHO DRC",weight=1)
goarn_network.add_edge("WHO DRC", "World Food Programme",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "NICD South Africa",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "NICD South Africa",weight=1)
goarn_network.add_edge("MSF Belgium", "NICD South Africa",weight=1)
goarn_network.add_edge("NICD South Africa", "UNICEF",weight=1)
goarn_network.add_edge("MONUC", "NICD South Africa",weight=1)
goarn_network.add_edge("NICD South Africa", "World Food Programme",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "Congolese Red Cross (DRC)",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "MSF Belgium",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "UNICEF",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "MONUC",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "World Food Programme",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "MSF Belgium",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "UNICEF",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "MONUC",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "World Food Programme",weight=1)
goarn_network.add_edge("MSF Belgium", "UNICEF",weight=1)
goarn_network.add_edge("MSF Belgium", "World Food Programme",weight=1)
goarn_network.add_edge("MONUC", "UNICEF",weight=1)
goarn_network.add_edge("MONUC", "World Food Programme",weight=1)

#import csv
#with open("/Users/grizzlemuff/Documents/SI608/GOARN/bloodborne.csv", 'wb') as csvfile:
#    spamwriter = csv.writer(csvfile)
#    spamwriter.writerow('D')
#    centrality=  nx.degree_centrality(goarn_network)
#    for each in centrality.items():
#        print 'Degree Centrality: ', each[0], each[1]
#        print each
#        spamwriter.writerow([each[0], each[1]])
#    
#    spamwriter.writerow('C')
#    close=nx.closeness_centrality(goarn_network)    
#    for each in close.items():
#        print 'Closeness Centrality: ', each[0], '\t', each[1]
#        spamwriter.writerow([each[0], each[1]])
#
#    spamwriter.writerow('B')
#    btwn=nx.betweenness_centrality(goarn_network, weight='weight')
#    for each in btwn.items():
#        print 'Betweeness Centrality: ', each[0], each[1]
#        spamwriter.writerow([each[0], each[1]])
#
#    avg_clust= nx.average_clustering(goarn_network)
#    print 'Average Clustering: ', avg_clust
#    
#
#
#
#    clustering = nx.clustering(goarn_network)
#
#    spamwriter.writerow('L')
#    for each in clustering.items():
#        print 'Clustering Coefficient per Node: ', each[0], each[1]
#        spamwriter.writerow([each[0], each[1]])
#    csvfile.close()
#
#
#nx.draw_spring(goarn_network)
#plt.show()


##Histogram of degree distribution
#d = nx.degree(goarn_network)
#plt.hist(d.values())
#plt.show()


#def most_important(G):
# """ returns a copy of G with
#     the most important nodes
#     according to the pagerank """ 
# ranking = nx.betweenness_centrality(G).items()
# print ranking
# r = [x[1] for x in ranking]
# m = sum(r)/len(r) # mean centrality
# t = m*3 # threshold, we keep only the nodes with 3 times the mean
# Gt = G.copy()
# for k, v in ranking:
#  if v < t:
#   Gt.remove_node(k)
# return Gt
#
#Gt = most_important(goarn_network) # trimming
#
#from pylab import show
## create the layout
#pos = nx.spring_layout(goarn_network)
## draw the nodes and the edges (all)
#nx.draw_networkx_nodes(goarn_network,pos,node_color='b',alpha=0.2,node_size=8)
#nx.draw_networkx_edges(goarn_network,pos,alpha=0.1)
#
## draw the most important nodes with a different style
#nx.draw_networkx_nodes(Gt,pos,node_color='r',alpha=0.4,node_size=254)
## also the labels this time
#nx.draw_networkx_labels(Gt,pos,font_size=12,font_color='b')
#show()


from networkx import find_cliques
cliques = list(find_cliques(goarn_network))
bigg= max(cliques, key=lambda l: len(l))
print bigg
print nx.graph_number_of_cliques(goarn_network, cliques)

H=nx.connected_component_subgraphs(goarn_network)[0]
print(nx.average_shortest_path_length(H))

print len(goarn_network.nodes())