import networkx as nx
import matplotlib.pyplot as plt
goarn_network= nx.Graph()

goarn_network.add_edge("Epicentre France", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO HQ",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Epicentre France", "WHO HQ",weight=2)
goarn_network.add_edge("Epicentre France", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("WHO Collaborating Centre", "WHO HQ",weight=3)
goarn_network.add_edge("MSF Belgium", "MSF Holland",weight=1)
goarn_network.add_edge("MSF Belgium", "MSF Switzerland",weight=2)
goarn_network.add_edge("MSF Belgium", "MSF France",weight=1)
goarn_network.add_edge("Institut National de Recherche Biomedicale", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO Ethiopia",weight=1)
goarn_network.add_edge("MSF Belgium", "Red Crescent societies",weight=2)
goarn_network.add_edge("MSF Belgium", "WHO HQ",weight=2)
goarn_network.add_edge("MSF Holland", "MSF Switzerland",weight=1)
goarn_network.add_edge("MSF France", "MSF Holland",weight=1)
goarn_network.add_edge("Institut National de Recherche Biomedicale", "MSF Holland",weight=1)
goarn_network.add_edge("MSF Holland", "WHO Ethiopia",weight=1)
goarn_network.add_edge("MSF Holland", "Red Crescent societies",weight=4)
goarn_network.add_edge("MSF Holland", "WHO HQ",weight=1)
goarn_network.add_edge("MSF France", "MSF Switzerland",weight=1)
goarn_network.add_edge("Institut National de Recherche Biomedicale", "MSF Switzerland",weight=1)
goarn_network.add_edge("MSF Switzerland", "WHO Ethiopia",weight=1)
goarn_network.add_edge("MSF Switzerland", "Red Crescent societies",weight=1)
goarn_network.add_edge("MSF Switzerland", "WHO HQ",weight=2)
goarn_network.add_edge("Institut National de Recherche Biomedicale", "MSF France",weight=1)
goarn_network.add_edge("MSF France", "WHO Ethiopia",weight=1)
goarn_network.add_edge("MSF France", "Red Crescent societies",weight=1)
goarn_network.add_edge("MSF France", "WHO HQ",weight=1)
goarn_network.add_edge("Institut National de Recherche Biomedicale", "WHO Ethiopia",weight=1)
goarn_network.add_edge("Institut National de Recherche Biomedicale", "Red Crescent societies",weight=1)
goarn_network.add_edge("Institut National de Recherche Biomedicale", "WHO HQ",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO Ethiopia",weight=1)
goarn_network.add_edge("WHO Ethiopia", "WHO HQ",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO HQ",weight=4)
goarn_network.add_edge("WHO Bangladesh", "WHO HQ",weight=1)
goarn_network.add_edge("Field Epidemiology Training Programme", "WHO HQ",weight=1)
goarn_network.add_edge("ICDDR_B", "WHO HQ",weight=2)
goarn_network.add_edge("Field Epidemiology Training Programme", "WHO Bangladesh",weight=1)
goarn_network.add_edge("ICDDR_B", "WHO Bangladesh",weight=2)
goarn_network.add_edge("Field Epidemiology Training Programme", "ICDDR_B",weight=2)
goarn_network.add_edge("ICDDR_B", "ICDDR_B",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO Kosovo",weight=2)
goarn_network.add_edge("Institute of Public Health Kosovo", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("North Manchester General Hospital", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("Institute of Public Health Kosovo", "WHO Kosovo",weight=1)
goarn_network.add_edge("North Manchester General Hospital", "WHO Kosovo",weight=1)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "WHO Kosovo",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "WHO Kosovo",weight=1)
goarn_network.add_edge("Institute of Public Health Kosovo", "North Manchester General Hospital",weight=1)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "Institute of Public Health Kosovo",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "Institute of Public Health Kosovo",weight=1)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "North Manchester General Hospital",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "North Manchester General Hospital",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "Department of Infectious Diseases Kosovo",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "WHO HQ",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "UNICEF",weight=1)
goarn_network.add_edge("MSF", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Epicentre France", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC France", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "Red Crescent societies",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("UNICEF", "WHO HQ",weight=2)
goarn_network.add_edge("MSF", "WHO HQ",weight=2)
goarn_network.add_edge("CDC France", "WHO HQ",weight=1)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO HQ",weight=1)
goarn_network.add_edge("Red Crescent Societies", "WHO HQ",weight=1)
goarn_network.add_edge("ECHO", "WHO HQ",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "WHO HQ",weight=1)
goarn_network.add_edge("MSF", "UNICEF",weight=5)
goarn_network.add_edge("Epicentre France", "UNICEF",weight=1)
goarn_network.add_edge("UNICEF", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("CDC France", "UNICEF",weight=1)
goarn_network.add_edge("UNICEF", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Red Crescent societies", "UNICEF",weight=4)
goarn_network.add_edge("Red Crescent Societies", "UNICEF",weight=1)
goarn_network.add_edge("ECHO", "UNICEF",weight=4)
goarn_network.add_edge("National Institute for Public Health (INHP)", "UNICEF",weight=1)
goarn_network.add_edge("Epicentre France", "MSF",weight=1)
goarn_network.add_edge("MSF", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("CDC France", "MSF",weight=1)
goarn_network.add_edge("MSF", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("MSF", "Red Crescent societies",weight=3)
goarn_network.add_edge("MSF", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "MSF",weight=2)
goarn_network.add_edge("MSF", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("CDC France", "Epicentre France",weight=1)
goarn_network.add_edge("Epicentre France", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Epicentre France", "Red Crescent societies",weight=1)
goarn_network.add_edge("Epicentre France", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "Epicentre France",weight=1)
goarn_network.add_edge("Epicentre France", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("CDC France", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO Collaborating Centre",weight=3)
goarn_network.add_edge("Red Crescent Societies", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("ECHO", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC France", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("CDC France", "Red Crescent societies",weight=1)
goarn_network.add_edge("CDC France", "Red Crescent Societies",weight=1)
goarn_network.add_edge("CDC France", "ECHO",weight=1)
goarn_network.add_edge("CDC France", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("Red Crescent societies", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Red Crescent Societies", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("ECHO", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Red Crescent Societies", "Red Crescent societies",weight=1)
goarn_network.add_edge("ECHO", "Red Crescent societies",weight=5)
goarn_network.add_edge("National Institute for Public Health (INHP)", "Red Crescent societies",weight=1)
goarn_network.add_edge("ECHO", "Red Crescent Societies",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("Ministry of Health Guinea", "WHO Georgia",weight=1)
goarn_network.add_edge("CIRMF", "WHO Gabon",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO Gabon",weight=1)
goarn_network.add_edge("CIRMF", "MSF Belgium",weight=2)
goarn_network.add_edge("Ministry of Health", "WHO",weight=1)
goarn_network.add_edge("MSF Belgium", "Ministry of Health",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO",weight=2)
goarn_network.add_edge("Institut Pasteur Dakar", "Ministry of Health Senegal ",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "WHO HQ",weight=1)
goarn_network.add_edge("ICG", "Institut Pasteur Dakar",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "MSF",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "Red Crescent societies",weight=2)
goarn_network.add_edge("Institut Pasteur Dakar", "UNICEF",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "WHO_AFRO",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "WHO HQ",weight=1)
goarn_network.add_edge("ICG", "Ministry of Health Senegal ",weight=1)
goarn_network.add_edge("MSF", "Ministry of Health Senegal ",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "Red Crescent societies",weight=2)
goarn_network.add_edge("Ministry of Health Senegal ", "UNICEF",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO_AFRO",weight=1)
goarn_network.add_edge("ICG", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("WHO HQ", "WHO_AFRO",weight=2)
goarn_network.add_edge("ICG", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF", "WHO_AFRO",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO_AFRO",weight=6)
goarn_network.add_edge("UNICEF", "WHO_AFRO",weight=3)
goarn_network.add_edge("ICG", "WHO HQ",weight=1)
goarn_network.add_edge("ICG", "MSF",weight=2)
goarn_network.add_edge("ICG", "Red Crescent societies",weight=2)
goarn_network.add_edge("ICG", "UNICEF",weight=2)
goarn_network.add_edge("Red Crescent societies", "Red Crescent societies",weight=4)
goarn_network.add_edge("Global Influenza Surveillance Network", "Hong Kong National Influenza Center",weight=3)
goarn_network.add_edge("Department of Health in Hong Kong", "Hong Kong National Influenza Center",weight=1)
goarn_network.add_edge("Hong Kong National Influenza Center", "Ministry of Health in Beijing",weight=1)
goarn_network.add_edge("Department of Health in Hong Kong", "Global Influenza Surveillance Network",weight=1)
goarn_network.add_edge("Global Influenza Surveillance Network", "Ministry of Health in Beijing",weight=1)
goarn_network.add_edge("Department of Health in Hong Kong", "Ministry of Health in Beijing",weight=1)
goarn_network.add_edge("Ministry of Health in Singapore", "WHO",weight=1)
goarn_network.add_edge("Chinese Ministry of Health", "WHO China",weight=1)
goarn_network.add_edge("CDC Taiwan", "WHO",weight=1)
goarn_network.add_edge("Ministry of Health Algeria", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Ministry of Health Algeria",weight=1)
goarn_network.add_edge("Kazakh Scientific Centre for Quarantine and Zoonotic Disease", "Ministry of Health Algeria",weight=1)
goarn_network.add_edge("Institut Pasteur France", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Kazakh Scientific Centre for Quarantine and Zoonotic Disease", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Kazakh Scientific Centre for Quarantine and Zoonotic Disease",weight=1)
goarn_network.add_edge("MSF Luxembourg", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("IRD", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("CIRMF", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO_AFRO",weight=2)
goarn_network.add_edge("Ministry of Health DRC", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("MSF Holland", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "National Control Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("ECHO", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("French Cooperation", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "Red Crescent societies",weight=3)
goarn_network.add_edge("Ministry of Health DRC", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("CIRMF", "IRD",weight=1)
goarn_network.add_edge("IRD", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("IRD", "WHO_AFRO",weight=1)
goarn_network.add_edge("IRD", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("IRD", "MSF Holland",weight=1)
goarn_network.add_edge("IRD", "National Control Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "IRD",weight=1)
goarn_network.add_edge("ECHO", "IRD",weight=1)
goarn_network.add_edge("French Cooperation", "IRD",weight=1)
goarn_network.add_edge("IRD", "Red Crescent societies",weight=3)
goarn_network.add_edge("IRD", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("CIRMF", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("CIRMF", "WHO_AFRO",weight=1)
goarn_network.add_edge("CIRMF", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("CIRMF", "MSF Holland",weight=1)
goarn_network.add_edge("CIRMF", "National Control Committee DRC",weight=1)
goarn_network.add_edge("CIRMF", "Congolese Ministries of Defence and Foresty",weight=1)
goarn_network.add_edge("CIRMF", "ECHO",weight=1)
goarn_network.add_edge("CIRMF", "French Cooperation",weight=1)
goarn_network.add_edge("CIRMF", "Red Crescent societies",weight=3)
goarn_network.add_edge("CIRMF", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("National Coordination Committee DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("National Coordination Committee DRC", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("MSF Holland", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("National Control Committee DRC", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("ECHO", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("French Cooperation", "National Coordination Committee DRC",weight=1)
goarn_network.add_edge("National Coordination Committee DRC", "Red Crescent societies",weight=3)
goarn_network.add_edge("National Coordination Committee DRC", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("WHO Congo Brazzaville", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Holland", "WHO_AFRO",weight=1)
goarn_network.add_edge("National Control Committee DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "WHO_AFRO",weight=1)
goarn_network.add_edge("ECHO", "WHO_AFRO",weight=3)
goarn_network.add_edge("French Cooperation", "WHO_AFRO",weight=1)
goarn_network.add_edge("United Nations High Commission for Refugees (UNHCR)", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Holland", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("National Control Committee DRC", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("ECHO", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("French Cooperation", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO Congo Brazzaville",weight=3)
goarn_network.add_edge("United Nations High Commission for Refugees (UNHCR)", "WHO Congo Brazzaville",weight=1)
goarn_network.add_edge("MSF Holland", "National Control Committee DRC",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "MSF Holland",weight=1)
goarn_network.add_edge("ECHO", "MSF Holland",weight=1)
goarn_network.add_edge("French Cooperation", "MSF Holland",weight=1)
goarn_network.add_edge("MSF Holland", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "National Control Committee DRC",weight=1)
goarn_network.add_edge("ECHO", "National Control Committee DRC",weight=1)
goarn_network.add_edge("French Cooperation", "National Control Committee DRC",weight=1)
goarn_network.add_edge("National Control Committee DRC", "Red Crescent societies",weight=3)
goarn_network.add_edge("National Control Committee DRC", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "ECHO",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "French Cooperation",weight=1)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "Red Crescent societies",weight=3)
goarn_network.add_edge("Congolese Ministries of Defence and Foresty", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("ECHO", "French Cooperation",weight=1)
goarn_network.add_edge("ECHO", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("French Cooperation", "Red Crescent societies",weight=3)
goarn_network.add_edge("French Cooperation", "United Nations High Commission for Refugees (UNHCR)",weight=1)
goarn_network.add_edge("Red Crescent societies", "United Nations High Commission for Refugees (UNHCR)",weight=3)
goarn_network.add_edge("Hong Kong National Influenza Center", "Japan National Institute for Infectious Diseases",weight=1)
goarn_network.add_edge("Global Influenza Surveillance Network", "Japan National Institute for Infectious Diseases",weight=2)
goarn_network.add_edge("Global Influenza Surveillance Network", "Global Influenza Surveillance Network",weight=1)
goarn_network.add_edge("OIE", "WHO HQ",weight=1)
goarn_network.add_edge("FAO", "WHO HQ",weight=1)
goarn_network.add_edge("WHO HQ", "WHO Thailand",weight=1)
goarn_network.add_edge("Ministry of Health Thailand", "WHO HQ",weight=1)
goarn_network.add_edge("FAO", "OIE",weight=4)
goarn_network.add_edge("OIE", "WHO Thailand",weight=1)
goarn_network.add_edge("Ministry of Health Thailand", "OIE",weight=1)
goarn_network.add_edge("FAO", "WHO Thailand",weight=1)
goarn_network.add_edge("FAO", "Ministry of Health Thailand",weight=1)
goarn_network.add_edge("Ministry of Health Thailand", "WHO Thailand",weight=1)
goarn_network.add_edge("OIE", "WHO",weight=3)
goarn_network.add_edge("FAO", "WHO",weight=5)
goarn_network.add_edge("Ministray of Health Bangladesh", "WHO",weight=1)
goarn_network.add_edge("WHO", "WHO HQ",weight=1)
goarn_network.add_edge("NATIONAL HEALTH LABORATORY SERVICE (NHLS)", "WHO HQ",weight=1)
goarn_network.add_edge("NATIONAL HEALTH LABORATORY SERVICE (NHLS)", "WHO",weight=1)
goarn_network.add_edge("WHO", "WHO Thailand",weight=2)
goarn_network.add_edge("Queen Sirikit National Institute of Child Health-Bangkok", "WHO",weight=2)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO",weight=2)
goarn_network.add_edge("Queen Sirikit National Institute of Child Health-Bangkok", "WHO Thailand",weight=2)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO Thailand",weight=2)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "Queen Sirikit National Institute of Child Health-Bangkok",weight=2)
goarn_network.add_edge("WHO DRC", "WHO HQ",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO HQ",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO HQ",weight=1)
goarn_network.add_edge("Medair", "WHO HQ",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO HQ",weight=1)
goarn_network.add_edge("WHO DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO DRC",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO DRC",weight=2)
goarn_network.add_edge("MSF Switzerland", "WHO DRC",weight=1)
goarn_network.add_edge("Medair", "WHO DRC",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO_AFRO",weight=2)
goarn_network.add_edge("MSF Switzerland", "WHO_AFRO",weight=1)
goarn_network.add_edge("Medair", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("MSF Belgium", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("MSF Switzerland", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Medair", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "MSF Belgium",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "MSF Switzerland",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Medair",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Institut de la Recherche Biomedicale",weight=1)
goarn_network.add_edge("MSF Belgium", "Medair",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Switzerland", "Medair",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "MSF Switzerland",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "Medair",weight=1)
goarn_network.add_edge("UNICEF", "WHO",weight=5)
goarn_network.add_edge("GAVI", "WHO",weight=4)
goarn_network.add_edge("WHO", "WHO_AFRO",weight=1)
goarn_network.add_edge("ECHO", "WHO",weight=2)
goarn_network.add_edge("Red Crescent societies", "WHO",weight=1)
goarn_network.add_edge("MSF Belgium", "UNICEF",weight=2)
goarn_network.add_edge("GAVI", "MSF Belgium",weight=1)
goarn_network.add_edge("ECHO", "MSF Belgium",weight=1)
goarn_network.add_edge("GAVI", "UNICEF",weight=3)
goarn_network.add_edge("GAVI", "WHO_AFRO",weight=1)
goarn_network.add_edge("ECHO", "GAVI",weight=2)
goarn_network.add_edge("GAVI", "Red Crescent societies",weight=1)
goarn_network.add_edge("MSF", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("Ministry of Health Mali", "WHO",weight=1)
goarn_network.add_edge("ICG", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("GAVI", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("Ministry of Health Mali", "UNICEF",weight=1)
goarn_network.add_edge("ECHO", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("MSF", "WHO",weight=2)
goarn_network.add_edge("GAVI", "MSF",weight=2)
goarn_network.add_edge("ICG", "WHO",weight=1)
goarn_network.add_edge("GAVI", "ICG",weight=1)
goarn_network.add_edge("ECHO", "ICG",weight=1)
goarn_network.add_edge("Minister of Health Turkey", "WHO collaborating laboratory UK",weight=1)
goarn_network.add_edge("WHO collaborating laboratory UK", "WHO_Euro",weight=1)
goarn_network.add_edge("MRC National Institute for Medical Research in Mill Hill London", "WHO collaborating laboratory UK",weight=1)
goarn_network.add_edge("Minister of Health Turkey", "WHO_Euro",weight=1)
goarn_network.add_edge("MRC National Institute for Medical Research in Mill Hill London", "Minister of Health Turkey",weight=1)
goarn_network.add_edge("MRC National Institute for Medical Research in Mill Hill London", "WHO_Euro",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO Togo",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO_AFRO",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "UNICEF",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "ECHO",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "Togolese Red Cross",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "Federation of Red Cross and Red Crescent Societies",weight=1)
goarn_network.add_edge("WHO Mediterranean Centre for Vulnerability Reduction (WMC)", "WHO Togo",weight=1)
goarn_network.add_edge("WHO Mediterranean Centre for Vulnerability Reduction (WMC)", "WHO_AFRO",weight=1)
goarn_network.add_edge("WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("UNICEF", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("ECHO", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("WHO Togo", "WHO_AFRO",weight=1)
goarn_network.add_edge("WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control", "WHO Togo",weight=1)
goarn_network.add_edge("UNICEF", "WHO Togo",weight=1)
goarn_network.add_edge("ECHO", "WHO Togo",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO Togo",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO Togo",weight=1)
goarn_network.add_edge("WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control", "WHO_AFRO",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO_AFRO",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO_AFRO",weight=1)
goarn_network.add_edge("UNICEF", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("ECHO", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Togolese Red Cross", "UNICEF",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "UNICEF",weight=1)
goarn_network.add_edge("ECHO", "Togolese Red Cross",weight=1)
goarn_network.add_edge("ECHO", "Federation of Red Cross and Red Crescent Societies",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "Togolese Red Cross",weight=1)
goarn_network.add_edge("FAO", "NAMRU-3 Egypt",weight=2)
goarn_network.add_edge("NAMRU-3 Egypt", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("NAMRU-3 Egypt", "WHO_EMRO",weight=1)
goarn_network.add_edge("NAMRU-3 Egypt", "WHO",weight=5)
goarn_network.add_edge("FAO", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("FAO", "WHO_EMRO",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO_EMRO",weight=1)
goarn_network.add_edge("WHO", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("WHO", "WHO_EMRO",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "WHO Uganda",weight=1)
goarn_network.add_edge("Ministry of Health of Uganda", "UNICEF",weight=1)
goarn_network.add_edge("MSF", "Ministry of Health of Uganda",weight=1)
goarn_network.add_edge("UNICEF", "WHO Uganda",weight=1)
goarn_network.add_edge("MSF", "WHO Uganda",weight=1)
goarn_network.add_edge("IOM", "WHO",weight=1)
goarn_network.add_edge("OXFAM-GB", "WHO",weight=1)
goarn_network.add_edge("Medecins du Monde", "WHO",weight=1)
goarn_network.add_edge("ICRC", "WHO",weight=1)
goarn_network.add_edge("ACF", "WHO",weight=1)
goarn_network.add_edge("MSF Spain", "WHO",weight=1)
goarn_network.add_edge("MSF Holland", "WHO",weight=1)
goarn_network.add_edge("MSF Luxemburg", "WHO",weight=1)
goarn_network.add_edge("Plan International", "WHO",weight=1)
goarn_network.add_edge("GOAL", "WHO",weight=1)
goarn_network.add_edge("Save the Children-UK", "WHO",weight=1)
goarn_network.add_edge("IOM", "UNICEF",weight=1)
goarn_network.add_edge("OXFAM-GB", "UNICEF",weight=1)
goarn_network.add_edge("Medecins du Monde", "UNICEF",weight=1)
goarn_network.add_edge("ICRC", "UNICEF",weight=1)
goarn_network.add_edge("ACF", "UNICEF",weight=1)
goarn_network.add_edge("MSF Spain", "UNICEF",weight=1)
goarn_network.add_edge("MSF Holland", "UNICEF",weight=1)
goarn_network.add_edge("MSF Luxemburg", "UNICEF",weight=1)
goarn_network.add_edge("Plan International", "UNICEF",weight=1)
goarn_network.add_edge("GOAL", "UNICEF",weight=1)
goarn_network.add_edge("Save the Children-UK", "UNICEF",weight=1)
goarn_network.add_edge("IOM", "OXFAM-GB",weight=1)
goarn_network.add_edge("IOM", "Medecins du Monde",weight=1)
goarn_network.add_edge("ICRC", "IOM",weight=1)
goarn_network.add_edge("ACF", "IOM",weight=1)
goarn_network.add_edge("IOM", "MSF Spain",weight=1)
goarn_network.add_edge("IOM", "MSF Holland",weight=1)
goarn_network.add_edge("IOM", "MSF Luxemburg",weight=1)
goarn_network.add_edge("IOM", "Plan International",weight=1)
goarn_network.add_edge("GOAL", "IOM",weight=1)
goarn_network.add_edge("IOM", "Save the Children-UK",weight=1)
goarn_network.add_edge("Medecins du Monde", "OXFAM-GB",weight=1)
goarn_network.add_edge("ICRC", "OXFAM-GB",weight=1)
goarn_network.add_edge("ACF", "OXFAM-GB",weight=1)
goarn_network.add_edge("MSF Spain", "OXFAM-GB",weight=1)
goarn_network.add_edge("MSF Holland", "OXFAM-GB",weight=1)
goarn_network.add_edge("MSF Luxemburg", "OXFAM-GB",weight=1)
goarn_network.add_edge("OXFAM-GB", "Plan International",weight=1)
goarn_network.add_edge("GOAL", "OXFAM-GB",weight=1)
goarn_network.add_edge("OXFAM-GB", "Save the Children-UK",weight=1)
goarn_network.add_edge("ICRC", "Medecins du Monde",weight=1)
goarn_network.add_edge("ACF", "Medecins du Monde",weight=1)
goarn_network.add_edge("MSF Spain", "Medecins du Monde",weight=1)
goarn_network.add_edge("MSF Holland", "Medecins du Monde",weight=1)
goarn_network.add_edge("MSF Luxemburg", "Medecins du Monde",weight=1)
goarn_network.add_edge("Medecins du Monde", "Plan International",weight=1)
goarn_network.add_edge("GOAL", "Medecins du Monde",weight=1)
goarn_network.add_edge("Medecins du Monde", "Save the Children-UK",weight=1)
goarn_network.add_edge("ACF", "ICRC",weight=1)
goarn_network.add_edge("ICRC", "MSF Spain",weight=1)
goarn_network.add_edge("ICRC", "MSF Holland",weight=1)
goarn_network.add_edge("ICRC", "MSF Luxemburg",weight=1)
goarn_network.add_edge("ICRC", "Plan International",weight=1)
goarn_network.add_edge("GOAL", "ICRC",weight=1)
goarn_network.add_edge("ICRC", "Save the Children-UK",weight=1)
goarn_network.add_edge("ACF", "MSF Spain",weight=1)
goarn_network.add_edge("ACF", "MSF Holland",weight=1)
goarn_network.add_edge("ACF", "MSF Luxemburg",weight=1)
goarn_network.add_edge("ACF", "Plan International",weight=1)
goarn_network.add_edge("ACF", "GOAL",weight=1)
goarn_network.add_edge("ACF", "Save the Children-UK",weight=1)
goarn_network.add_edge("MSF Holland", "MSF Spain",weight=1)
goarn_network.add_edge("MSF Luxemburg", "MSF Spain",weight=1)
goarn_network.add_edge("MSF Spain", "Plan International",weight=1)
goarn_network.add_edge("GOAL", "MSF Spain",weight=1)
goarn_network.add_edge("MSF Spain", "Save the Children-UK",weight=1)
goarn_network.add_edge("MSF Holland", "MSF Luxemburg",weight=1)
goarn_network.add_edge("MSF Holland", "Plan International",weight=1)
goarn_network.add_edge("GOAL", "MSF Holland",weight=1)
goarn_network.add_edge("MSF Holland", "Save the Children-UK",weight=1)
goarn_network.add_edge("MSF Luxemburg", "Plan International",weight=1)
goarn_network.add_edge("GOAL", "MSF Luxemburg",weight=1)
goarn_network.add_edge("MSF Luxemburg", "Save the Children-UK",weight=1)
goarn_network.add_edge("GOAL", "Plan International",weight=1)
goarn_network.add_edge("Plan International", "Save the Children-UK",weight=1)
goarn_network.add_edge("GOAL", "Save the Children-UK",weight=1)
goarn_network.add_edge("CIRMF", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("CIRMF", "WHO DRC",weight=1)
goarn_network.add_edge("CIRMF", "NICD South Africa",weight=1)
goarn_network.add_edge("CIRMF", "Caritas (Belgium)",weight=1)
goarn_network.add_edge("CIRMF", "Congolese Red Cross (DRC)",weight=1)
goarn_network.add_edge("CIRMF", "UNICEF",weight=1)
goarn_network.add_edge("CIRMF", "MONUC",weight=1)
goarn_network.add_edge("CIRMF", "World Food Programme",weight=1)
goarn_network.add_edge("National de Recherches Biologiques (INRB)", "WHO DRC",weight=1)
goarn_network.add_edge("NICD South Africa", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("MSF Belgium", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("National de Recherches Biologiques (INRB)", "UNICEF",weight=1)
goarn_network.add_edge("MONUC", "National de Recherches Biologiques (INRB)",weight=1)
goarn_network.add_edge("National de Recherches Biologiques (INRB)", "World Food Programme",weight=1)
goarn_network.add_edge("NICD South Africa", "WHO DRC",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "WHO DRC",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "WHO DRC",weight=1)
goarn_network.add_edge("UNICEF", "WHO DRC",weight=1)
goarn_network.add_edge("MONUC", "WHO DRC",weight=1)
goarn_network.add_edge("WHO DRC", "World Food Programme",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "NICD South Africa",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "NICD South Africa",weight=1)
goarn_network.add_edge("MSF Belgium", "NICD South Africa",weight=1)
goarn_network.add_edge("NICD South Africa", "UNICEF",weight=1)
goarn_network.add_edge("MONUC", "NICD South Africa",weight=1)
goarn_network.add_edge("NICD South Africa", "World Food Programme",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "Congolese Red Cross (DRC)",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "MSF Belgium",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "UNICEF",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "MONUC",weight=1)
goarn_network.add_edge("Caritas (Belgium)", "World Food Programme",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "MSF Belgium",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "UNICEF",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "MONUC",weight=1)
goarn_network.add_edge("Congolese Red Cross (DRC)", "World Food Programme",weight=1)
goarn_network.add_edge("MONUC", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Belgium", "World Food Programme",weight=1)
goarn_network.add_edge("MONUC", "UNICEF",weight=1)
goarn_network.add_edge("UNICEF", "World Food Programme",weight=1)
goarn_network.add_edge("MONUC", "World Food Programme",weight=1)
goarn_network.add_edge("NAMRU-3 Egypt", "UNICEF",weight=1)
goarn_network.add_edge("FAO", "UNICEF",weight=1)
goarn_network.add_edge("OIE", "UNICEF",weight=1)
goarn_network.add_edge("CDC Iraq", "UNICEF",weight=1)
goarn_network.add_edge("UNICEF", "WHO United Kingdom",weight=1)
goarn_network.add_edge("NAMRU-3 Egypt", "OIE",weight=1)
goarn_network.add_edge("CDC Iraq", "NAMRU-3 Egypt",weight=1)
goarn_network.add_edge("NAMRU-3 Egypt", "WHO United Kingdom",weight=1)
goarn_network.add_edge("CDC Iraq", "WHO",weight=1)
goarn_network.add_edge("WHO", "WHO United Kingdom",weight=1)
goarn_network.add_edge("CDC Iraq", "FAO",weight=1)
goarn_network.add_edge("FAO", "WHO United Kingdom",weight=1)
goarn_network.add_edge("CDC Iraq", "OIE",weight=1)
goarn_network.add_edge("OIE", "WHO United Kingdom",weight=1)
goarn_network.add_edge("CDC Iraq", "WHO United Kingdom",weight=1)


#nx.draw(goarn_network, with_labels=False)
#plt.show()
#
#
#import csv
#with open("/Users/grizzlemuff/Documents/SI608/GOARN/no_CDC.csv", 'wb') as csvfile:
#    spamwriter = csv.writer(csvfile)
#    spamwriter.writerow('D')
#    centrality=  nx.degree_centrality(goarn_network)
#    for each in centrality.items():
#        print 'Degree Centrality: ', each[0], each[1]
#        print each
#        spamwriter.writerow([each[0], each[1]])
#    
#    spamwriter.writerow('C')
#    close=nx.closeness_centrality(goarn_network)    
#    for each in close.items():
#        print 'Closeness Centrality: ', each[0], '\t', each[1]
#        spamwriter.writerow([each[0], each[1]])
#
#    spamwriter.writerow('B')
#    btwn=nx.betweenness_centrality(goarn_network, weight='weight')
#    for each in btwn.items():
#        print 'Betweeness Centrality: ', each[0], each[1]
#        spamwriter.writerow([each[0], each[1]])
#
#    avg_clust= nx.average_clustering(goarn_network)
#    print 'Average Clustering: ', avg_clust
#    
#
#
#
#    clustering = nx.clustering(goarn_network)
#
#    spamwriter.writerow('L')
#    for each in clustering.items():
#        print 'Clustering Coefficient per Node: ', each[0], each[1]
#        spamwriter.writerow([each[0], each[1]])
#    csvfile.close()
#    
    
import numpy as np
import math as mt


##degree distribution
#plt.figure(1)
#d = nx.degree(goarn_network)
#print d.values()
#plt.hist(d.values(), bins=15)
#plt.show()




#http://glowingpython.blogspot.com/2012/11/first-steps-with-networx.html


#def trim_nodes(goarn_network,d):
# """ returns a copy of G without 
#     the nodes with a degree less than d """
# Gt = goarn_network.copy()
# dn = nx.degree(Gt)
# for n in Gt.nodes():
#  if dn[n] <= d:
#   Gt.remove_node(n)
# return Gt
#
##drawing the network without nodes with degree less than 10
#
#
#Gt = trim_nodes(goarn_network,10)
#plt.figure(3)
#plt.title("Network of nodes with at least degree of 10")
#nx.draw(Gt,node_size=0,node_color='w',edge_color='b',alpha=.2, font_size=8)
#plt.show()



#def most_important(G):
# """ returns a copy of G with
#     the most important nodes
#     according to the pagerank """ 
# ranking = nx.betweenness_centrality(G).items()
# print ranking
# r = [x[1] for x in ranking]
# m = sum(r)/len(r) # mean centrality
# t = m*3 # threshold, we keep only the nodes with 3 times the mean
# Gt = G.copy()
# for k, v in ranking:
#  if v < t:
#   Gt.remove_node(k)
# return Gt
#
#Gt = most_important(goarn_network) # trimming
#
#from pylab import show
## create the layout
#pos = nx.spring_layout(goarn_network)
## draw the nodes and the edges (all)
#nx.draw_networkx_nodes(goarn_network,pos,node_color='b',alpha=0.2,node_size=8)
#nx.draw_networkx_edges(goarn_network,pos,alpha=0.1)
#
## draw the most important nodes with a different style
#nx.draw_networkx_nodes(Gt,pos,node_color='r',alpha=0.4,node_size=254)
## also the labels this time
#nx.draw_networkx_labels(Gt,pos,font_size=12,font_color='b')
#show() 


###http://stackoverflow.com/questions/21921185/simple-fat-tailed-log-binning
##import numpy as np  
#import math as mt
#  
#degree_list=nx.degree(goarn_network).values()
#
#kmin=min(degree_list)
#kmax=max(degree_list)
#
#bins=[float(k) for k in range(kmin,kmax+2,1)]
#density, binedges = np.histogram(degree_list, bins=bins, density=True)
#bins = np.delete(bins, -1)
#
#
#
#logBins = np.logspace(np.log10(kmin), np.log10(kmax),num=20)
#logBinDensity, binedges = np.histogram(degree_list, bins=logBins, density=True)
#logBins = np.delete(logBins, -1)
#
#for x in range(len(logBins)):
#    logBins[x] = mt.ceil(logBins[x])
#
#fig = plt.figure()
#ax = fig.add_subplot(111)
#ax.set_xscale('log')
#ax.set_yscale('log')
#
##plt.plot(bins,density,'x',color='black')
#plt.plot(logBins,logBinDensity,'x',color='blue')
#plt.title("log binned degree distribution")
#plt.show()

H=nx.connected_component_subgraphs(goarn_network)[0]
print(nx.average_shortest_path_length(H))

nx.draw_spring(goarn_network, k=.96, with_labels=False)
plt.show()

print len(goarn_network.nodes())