import networkx as nx
import matplotlib.pyplot as plt
goarn_network= nx.Graph()

goarn_network.add_edge("Epicentre France", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO HQ",weight=1)
goarn_network.add_edge("National Institute of Virology (NIV-South Africa)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Epicentre France", "WHO HQ",weight=2)
goarn_network.add_edge("Epicentre France", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("WHO Collaborating Centre", "WHO HQ",weight=3)
goarn_network.add_edge("CDC Atlanta", "FAO",weight=1)
goarn_network.add_edge("CDC Atlanta", "NAMRU-3 Egypt",weight=1)
goarn_network.add_edge("CDC Atlanta", "National Health Laboratory Service (NHLS)",weight=1)
goarn_network.add_edge("CDC Atlanta", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("CDC Atlanta", "Ministry of Health Saudi Arabia",weight=1)
goarn_network.add_edge("FAO", "NAMRU-3 Egypt",weight=1)
goarn_network.add_edge("FAO", "National Health Laboratory Service (NHLS)",weight=1)
goarn_network.add_edge("FAO", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("FAO", "Ministry of Health Saudi Arabia",weight=1)
goarn_network.add_edge("NAMRU-3 Egypt", "National Health Laboratory Service (NHLS)",weight=1)
goarn_network.add_edge("NAMRU-3 Egypt", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("Ministry of Health Saudi Arabia", "NAMRU-3 Egypt",weight=1)
goarn_network.add_edge("National Health Laboratory Service (NHLS)", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("Ministry of Health Saudi Arabia", "National Health Laboratory Service (NHLS)",weight=1)
goarn_network.add_edge("Ministry of Health Saudi Arabia", "National Institute of Virology (NIV-South Africa)",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO Kosovo",weight=2)
goarn_network.add_edge("Institute of Public Health Kosovo", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("North Manchester General Hospital", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("Institute of Public Health Kosovo", "WHO Kosovo",weight=1)
goarn_network.add_edge("North Manchester General Hospital", "WHO Kosovo",weight=1)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "WHO Kosovo",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "WHO Kosovo",weight=1)
goarn_network.add_edge("Institute of Public Health Kosovo", "North Manchester General Hospital",weight=1)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "Institute of Public Health Kosovo",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "Institute of Public Health Kosovo",weight=1)
goarn_network.add_edge("Department of Infectious Diseases Kosovo", "North Manchester General Hospital",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "North Manchester General Hospital",weight=1)
goarn_network.add_edge("Clinic for Infectious Diseases Kosovo", "Department of Infectious Diseases Kosovo",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "WHO HQ",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "UNICEF",weight=1)
goarn_network.add_edge("MSF", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Epicentre France", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC France", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "Red Crescent societies",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "Ministry of Health Abidjan",weight=1)
goarn_network.add_edge("Ministry of Health Abidjan", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("UNICEF", "WHO HQ",weight=2)
goarn_network.add_edge("MSF", "WHO HQ",weight=2)
goarn_network.add_edge("CDC France", "WHO HQ",weight=1)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO HQ",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO HQ",weight=3)
goarn_network.add_edge("Red Crescent Societies", "WHO HQ",weight=1)
goarn_network.add_edge("ECHO", "WHO HQ",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "WHO HQ",weight=1)
goarn_network.add_edge("MSF", "UNICEF",weight=4)
goarn_network.add_edge("Epicentre France", "UNICEF",weight=1)
goarn_network.add_edge("UNICEF", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("CDC France", "UNICEF",weight=1)
goarn_network.add_edge("UNICEF", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Red Crescent societies", "UNICEF",weight=4)
goarn_network.add_edge("Red Crescent Societies", "UNICEF",weight=1)
goarn_network.add_edge("ECHO", "UNICEF",weight=4)
goarn_network.add_edge("National Institute for Public Health (INHP)", "UNICEF",weight=1)
goarn_network.add_edge("Epicentre France", "MSF",weight=1)
goarn_network.add_edge("MSF", "WHO Collaborating Centre",weight=2)
goarn_network.add_edge("CDC France", "MSF",weight=1)
goarn_network.add_edge("MSF", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("MSF", "Red Crescent societies",weight=3)
goarn_network.add_edge("MSF", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "MSF",weight=2)
goarn_network.add_edge("MSF", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("CDC France", "Epicentre France",weight=1)
goarn_network.add_edge("Epicentre France", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Epicentre France", "Red Crescent societies",weight=1)
goarn_network.add_edge("Epicentre France", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "Epicentre France",weight=1)
goarn_network.add_edge("Epicentre France", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("CDC France", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("United Kingdom Department for International Development (DFID)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO Collaborating Centre",weight=3)
goarn_network.add_edge("Red Crescent Societies", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("ECHO", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("CDC France", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("CDC France", "Red Crescent societies",weight=1)
goarn_network.add_edge("CDC France", "Red Crescent Societies",weight=1)
goarn_network.add_edge("CDC France", "ECHO",weight=1)
goarn_network.add_edge("CDC France", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("Red Crescent societies", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Red Crescent Societies", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("ECHO", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "United Kingdom Department for International Development (DFID)",weight=1)
goarn_network.add_edge("Red Crescent Societies", "Red Crescent societies",weight=1)
goarn_network.add_edge("ECHO", "Red Crescent societies",weight=2)
goarn_network.add_edge("National Institute for Public Health (INHP)", "Red Crescent societies",weight=1)
goarn_network.add_edge("ECHO", "Red Crescent Societies",weight=1)
goarn_network.add_edge("National Institute for Public Health (INHP)", "Red Crescent Societies",weight=1)
goarn_network.add_edge("ECHO", "National Institute for Public Health (INHP)",weight=1)
goarn_network.add_edge("Ministry of Health Guinea", "WHO Georgia",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "Ministry of Health Senegal ",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "WHO HQ",weight=1)
goarn_network.add_edge("ICG", "Institut Pasteur Dakar",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "MSF",weight=1)
goarn_network.add_edge("Institut Pasteur Dakar", "Red Crescent societies",weight=2)
goarn_network.add_edge("Institut Pasteur Dakar", "UNICEF",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "WHO_AFRO",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "WHO HQ",weight=1)
goarn_network.add_edge("ICG", "Ministry of Health Senegal ",weight=1)
goarn_network.add_edge("MSF", "Ministry of Health Senegal ",weight=1)
goarn_network.add_edge("Ministry of Health Senegal ", "Red Crescent societies",weight=2)
goarn_network.add_edge("Ministry of Health Senegal ", "UNICEF",weight=1)
goarn_network.add_edge("WHO Collaborating Centre", "WHO_AFRO",weight=1)
goarn_network.add_edge("ICG", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("WHO HQ", "WHO_AFRO",weight=2)
goarn_network.add_edge("ICG", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF", "WHO_AFRO",weight=1)
goarn_network.add_edge("Red Crescent societies", "WHO_AFRO",weight=3)
goarn_network.add_edge("UNICEF", "WHO_AFRO",weight=3)
goarn_network.add_edge("ICG", "WHO HQ",weight=1)
goarn_network.add_edge("ICG", "MSF",weight=2)
goarn_network.add_edge("ICG", "Red Crescent societies",weight=2)
goarn_network.add_edge("ICG", "UNICEF",weight=2)
goarn_network.add_edge("Red Crescent societies", "Red Crescent societies",weight=1)
goarn_network.add_edge("Ministry of Health Algeria", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Ministry of Health Algeria",weight=1)
goarn_network.add_edge("Kazakh Scientific Centre for Quarantine and Zoonotic Disease", "Ministry of Health Algeria",weight=1)
goarn_network.add_edge("Institut Pasteur France", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Kazakh Scientific Centre for Quarantine and Zoonotic Disease", "WHO Collaborating Centre",weight=1)
goarn_network.add_edge("Institut Pasteur France", "Kazakh Scientific Centre for Quarantine and Zoonotic Disease",weight=1)
goarn_network.add_edge("WHO", "WHO Thailand",weight=1)
goarn_network.add_edge("Queen Sirikit National Institute of Child Health-Bangkok", "WHO",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO",weight=1)
goarn_network.add_edge("Queen Sirikit National Institute of Child Health-Bangkok", "WHO Thailand",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "WHO Thailand",weight=1)
goarn_network.add_edge("National Institute for Infectious Diseases Japan", "Queen Sirikit National Institute of Child Health-Bangkok",weight=1)
goarn_network.add_edge("WHO DRC", "WHO HQ",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO HQ",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO HQ",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO HQ",weight=1)
goarn_network.add_edge("MSF Switzerland", "WHO HQ",weight=1)
goarn_network.add_edge("Medair", "WHO HQ",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO HQ",weight=1)
goarn_network.add_edge("WHO DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO DRC",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO DRC",weight=1)
goarn_network.add_edge("MSF Switzerland", "WHO DRC",weight=1)
goarn_network.add_edge("Medair", "WHO DRC",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO DRC",weight=1)
goarn_network.add_edge("Ministry of Health DRC", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "WHO_AFRO",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO_AFRO",weight=2)
goarn_network.add_edge("MSF Switzerland", "WHO_AFRO",weight=1)
goarn_network.add_edge("Medair", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "WHO_AFRO",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("MSF Belgium", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("MSF Switzerland", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Medair", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "Ministry of Health DRC",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "MSF Belgium",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "MSF Switzerland",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Medair",weight=1)
goarn_network.add_edge("Institut Pasteur Madagascar", "Institut de la Recherche Biomedicale",weight=1)
goarn_network.add_edge("MSF Belgium", "MSF Switzerland",weight=1)
goarn_network.add_edge("MSF Belgium", "Medair",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Switzerland", "Medair",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "MSF Switzerland",weight=1)
goarn_network.add_edge("Institut de la Recherche Biomedicale", "Medair",weight=1)
goarn_network.add_edge("MSF Belgium", "WHO",weight=1)
goarn_network.add_edge("UNICEF", "WHO",weight=3)
goarn_network.add_edge("GAVI", "WHO",weight=4)
goarn_network.add_edge("WHO", "WHO_AFRO",weight=1)
goarn_network.add_edge("ECHO", "WHO",weight=2)
goarn_network.add_edge("Red Crescent societies", "WHO",weight=1)
goarn_network.add_edge("MSF Belgium", "UNICEF",weight=1)
goarn_network.add_edge("GAVI", "MSF Belgium",weight=1)
goarn_network.add_edge("ECHO", "MSF Belgium",weight=1)
goarn_network.add_edge("MSF Belgium", "Red Crescent societies",weight=1)
goarn_network.add_edge("GAVI", "UNICEF",weight=3)
goarn_network.add_edge("GAVI", "WHO_AFRO",weight=1)
goarn_network.add_edge("ECHO", "GAVI",weight=2)
goarn_network.add_edge("GAVI", "Red Crescent societies",weight=1)
goarn_network.add_edge("ECHO", "WHO_AFRO",weight=2)
goarn_network.add_edge("MSF", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("Ministry of Health Mali", "WHO",weight=1)
goarn_network.add_edge("ICG", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("GAVI", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("Ministry of Health Mali", "UNICEF",weight=1)
goarn_network.add_edge("ECHO", "Ministry of Health Mali",weight=1)
goarn_network.add_edge("MSF", "WHO",weight=2)
goarn_network.add_edge("GAVI", "MSF",weight=2)
goarn_network.add_edge("ICG", "WHO",weight=1)
goarn_network.add_edge("GAVI", "ICG",weight=1)
goarn_network.add_edge("ECHO", "ICG",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO Togo",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO_AFRO",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "UNICEF",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "ECHO",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "Togolese Red Cross",weight=1)
goarn_network.add_edge("Agence de Medecine Preventive", "Federation of Red Cross and Red Crescent Societies",weight=1)
goarn_network.add_edge("WHO Mediterranean Centre for Vulnerability Reduction (WMC)", "WHO Togo",weight=1)
goarn_network.add_edge("WHO Mediterranean Centre for Vulnerability Reduction (WMC)", "WHO_AFRO",weight=1)
goarn_network.add_edge("WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("UNICEF", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("ECHO", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO Mediterranean Centre for Vulnerability Reduction (WMC)",weight=1)
goarn_network.add_edge("WHO Togo", "WHO_AFRO",weight=1)
goarn_network.add_edge("WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control", "WHO Togo",weight=1)
goarn_network.add_edge("UNICEF", "WHO Togo",weight=1)
goarn_network.add_edge("ECHO", "WHO Togo",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO Togo",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO Togo",weight=1)
goarn_network.add_edge("WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control", "WHO_AFRO",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO_AFRO",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO_AFRO",weight=1)
goarn_network.add_edge("UNICEF", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("ECHO", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Togolese Red Cross", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "WHO HQ International Coordinating Group (ICG) on Vaccine Provision for Yellow fever Control",weight=1)
goarn_network.add_edge("Togolese Red Cross", "UNICEF",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "UNICEF",weight=1)
goarn_network.add_edge("ECHO", "Togolese Red Cross",weight=1)
goarn_network.add_edge("ECHO", "Federation of Red Cross and Red Crescent Societies",weight=1)
goarn_network.add_edge("Federation of Red Cross and Red Crescent Societies", "Togolese Red Cross",weight=1)

#import csv
#with open("/Users/grizzlemuff/Documents/SI608/GOARN/vectorborne.csv", 'wb') as csvfile:
#    spamwriter = csv.writer(csvfile)
#    spamwriter.writerow('D')
#    centrality=  nx.degree_centrality(goarn_network)
#    for each in centrality.items():
#        print 'Degree Centrality: ', each[0], each[1]
#        print each
#        spamwriter.writerow([each[0], each[1]])
#    
#    spamwriter.writerow('C')
#    close=nx.closeness_centrality(goarn_network)    
#    for each in close.items():
#        print 'Closeness Centrality: ', each[0], '\t', each[1]
#        spamwriter.writerow([each[0], each[1]])
#
#    spamwriter.writerow('B')
#    btwn=nx.betweenness_centrality(goarn_network, weight='weight')
#    for each in btwn.items():
#        print 'Betweeness Centrality: ', each[0], each[1]
#        spamwriter.writerow([each[0], each[1]])
#
#    avg_clust= nx.average_clustering(goarn_network)
#    print 'Average Clustering: ', avg_clust
#    
#
#
#
#    clustering = nx.clustering(goarn_network)
#
#    spamwriter.writerow('L')
#    for each in clustering.items():
#        print 'Clustering Coefficient per Node: ', each[0], each[1]
#        spamwriter.writerow([each[0], each[1]])
#    csvfile.close()


H=nx.connected_component_subgraphs(goarn_network)[0]
print(nx.average_shortest_path_length(H))

nx.draw_spring(goarn_network)
plt.show()

print len(goarn_network.nodes())